### ISSUE TITLE
MorseString2String函数问题

### ISSUE THREAD

**Issue by GitHubForPP** [robert1207/morse_encode#2]
![Uploading image.png…]()
在MorseString2String函数的这个地方要加上长度判断，否则一部分符号会先识别成数字，例如":"

**Comment by robert1207** [comment]
你提到的源代码如下，并没有发现你所提的问题，还请详细举证。
if (true == morse2str(temp, &ch) && b < 5) {
    string[c++] = ch;
} else if (true == morse2mark(temp, &ch)) {
    string[c++] = ch;
} else if (true == morse2num(temp, &ch)) {
    string[c++] = ch;
} else {
    printf("has morse that not be decoded !\n");
}

**Comment by GitHubForPP** [comment]
![image](https://user-images.githubusercontent.com/17693228/64307350-62d44c80-cfc8-11e9-910e-1fafee0a531e.png)
这是运行您程序的结果；
字符 :  的摩斯码是---... 字符 8 的摩斯码是---.. 在摩斯码转字符的时候，由于判断顺序是先判断的num，所以会先将摩斯码---...识别为8，您现在所贴代码和我之前clone的morse.c中摩斯码转字符中的判断不一致，现在这样的判断是OK的，之前是这样的：
`if (true == morse2str(temp, &ch) && b < 5) {
				string[c++] = ch;
			} else if (true == morse2num(temp, &ch)) {  
				string[c++] = ch;
			} else if (true == morse2mark(temp, &ch)) {
				string[c++] = ch;
			} else {
				printf("has morse that not be decoded !\n");
			}`

**Comment by robert1207** [comment]
确实，现在的代码没有这个问题了，多谢提issues
